In [1]:
import json
import os

with open('acall_data.json') as f:
    data = json.load(f)

In [9]:
print(data['1'][0])

{'description': 'SQL은 데이터베이스의 모든 작업을 통제하는 비절차적 언어이다. 비절차적 언어는 사용자가 원하는 결과만 작성한 후 해당 작업이 어떻게 수행 되는지에 대해서는 고려하지 않아도 된다. SQL은 일반적인 데이터베이스 작업을 수행하기 위해 SQL 문장을 정의하고 있다.', 'keywords': ['SQL', '비절차적', '원하는 결과', 'SQL 문장'], 'questions': ['데이터베이스의 모든 작업을 통제하는 언어는 무엇인가?', 'SQL은 어떤 언어인가?', '비절차적 언어는 사용자의 무엇을 요구하는가?', 'SQL은 데이터베이스 작업을 수행하기 위해 무엇을 정의하는가?'], 'page_num': 1}

In [10]:
print(data['1'][0].keys())

dict_keys(['description', 'keywords', 'questions', 'page_num'])

In [12]:
print(data['1'][0]['description'])

SQL은 데이터베이스의 모든 작업을 통제하는 비절차적 언어이다. 비절차적 언어는 사용자가 원하는 결과만 작성한 후 해당 작업이 어떻게 수행 되는지에 대해서는 고려하지 않아도 된다. SQL은 일반적인 데이터베이스 작업을 수행하기 위해 SQL 문장을 정의하고 있다.

In [14]:
print(data['1'][0]['keywords'])

['SQL', '비절차적', '원하는 결과', 'SQL 문장']

In [15]:
print(data['1'][0]['questions'])

['데이터베이스의 모든 작업을 통제하는 언어는 무엇인가?', 'SQL은 어떤 언어인가?', '비절차적 언어는 사용자의 무엇을 요구하는가?', 'SQL은 데이터베이스 작업을 수행하기 위해 무엇을 정의하는가?']

In [16]:
print(data['1'][0]['page_num'])

1

In [26]:
class InputExample:
    """
    A single example for sequence classification
    """
    #description에 대응되는 내용을 물어봐도
    #질문에 대응되는 내용을 물어봐도
    #keyword로만 물어봐도
    #모두 대응되는 superapp 페이지로 가야함
    def __init__(self, description, keyword, question, label):
        self.description = description
        self.keyword = keyword
        self.question = question
        self.label = label #superapp page num

        
def _read_file(file_path): #파일을 어떤 식으로 저장해야할까?
        with open(file_path) as f:
            data = json.load(f)['1']
            return data
        
def _create_examples(data): #미구현
        examples = []
        for item in data:
            description = item['description']
            keywords = item['keywords']
            questions = item['questions']
            label = int(item['page_num'])
        
            assert description != "" and keywords != "" and questions != "" and label != ""
            # print(label)
            # print(keywords)
            # print(questions)
            
            assert len(keywords) == len(questions)
            # if not len(keywords) == len(questions):
            #     continue
            
            pair_num = len(keywords) #한 개의 description에 몇 개의 (keyword, question) 쌍이 들어있는지
            pair_examples = []
            for p in range(pair_num):
                keyword = keywords[p]
                question = questions[p]
                example = InputExample(description, keyword, question, label)
                pair_examples.append(example)
            examples.extend(pair_examples)
        return examples

    
data = _read_file('acall_data.json')
examples = _create_examples(data)

for i, e in enumerate(examples):
    print(f'{i+1} d : {e.description}, k : {e.keyword}, q : {e.question}, num : {e.label}')

1 d : SQL은 데이터베이스의 모든 작업을 통제하는 비절차적 언어이다. 비절차적 언어는 사용자가 원하는 결과만 작성한 후 해당 작업이 어떻게 수행 되는지에 대해서는 고려하지 않아도 된다. SQL은 일반적인 데이터베이스 작업을 수행하기 위해 SQL 문장을 정의하고 있다., k : SQL, q : 데이터베이스의 모든 작업을 통제하는 언어는 무엇인가?, num : 1
2 d : SQL은 데이터베이스의 모든 작업을 통제하는 비절차적 언어이다. 비절차적 언어는 사용자가 원하는 결과만 작성한 후 해당 작업이 어떻게 수행 되는지에 대해서는 고려하지 않아도 된다. SQL은 일반적인 데이터베이스 작업을 수행하기 위해 SQL 문장을 정의하고 있다., k : 비절차적, q : SQL은 어떤 언어인가?, num : 1
3 d : SQL은 데이터베이스의 모든 작업을 통제하는 비절차적 언어이다. 비절차적 언어는 사용자가 원하는 결과만 작성한 후 해당 작업이 어떻게 수행 되는지에 대해서는 고려하지 않아도 된다. SQL은 일반적인 데이터베이스 작업을 수행하기 위해 SQL 문장을 정의하고 있다., k : 원하는 결과, q : 비절차적 언어는 사용자의 무엇을 요구하는가?, num : 1
4 d : SQL은 데이터베이스의 모든 작업을 통제하는 비절차적 언어이다. 비절차적 언어는 사용자가 원하는 결과만 작성한 후 해당 작업이 어떻게 수행 되는지에 대해서는 고려하지 않아도 된다. SQL은 일반적인 데이터베이스 작업을 수행하기 위해 SQL 문장을 정의하고 있다., k : SQL 문장, q : SQL은 데이터베이스 작업을 수행하기 위해 무엇을 정의하는가?, num : 1
5 d : 데이터 정의어(이하 DDL)는 데이터 간에 관계를 정의하여 데이터베이스 구조를 설정하는 SQL문장이다. 기본적으로 스키마 객체를 생성, 변경, 제거하기 위해 사용되지만 DDL은 그 외 특권과 역할을 부여 및 감시 그리고 테이블 객체에 대한 최적화를 위한 명령어 또한 존재한다., k : 데이터 정의어, q : 데이터 간에 관계를 정의하여 데이터베이스 구조를 설정하는 SQL 문장 무엇인가?, num : 2
6 d : 데이터 정의어(이하 DDL)는 데이터 간에 관계를 정의하여 데이터베이스 구조를 설정하는 SQL문장이다. 기본적으로 스키마 객체를 생성, 변경, 제거하기 위해 사용되지만 DDL은 그 외 특권과 역할을 부여 및 감시 그리고 테이블 객체에 대한 최적화를 위한 명령어 또한 존재한다., k : 생성, 변경, 제거, q : 기본적으로 스키마 객체는 무엇을 하기위해 사용되는가?, num : 2
7 d : 데이터 정의어(이하 DDL)는 데이터 간에 관계를 정의하여 데이터베이스 구조를 설정하는 SQL문장이다. 기본적으로 스키마 객체를 생성, 변경, 제거하기 위해 사용되지만 DDL은 그 외 특권과 역할을 부여 및 감시 그리고 테이블 객체에 대한 최적화를 위한 명령어 또한 존재한다., k : 특권과 역할, q : 데이터 정의어는 그 외 어떤 것을 부여 및 감시 할 수 있는가?, num : 2
8 d : 데이터 정의어(이하 DDL)는 데이터 간에 관계를 정의하여 데이터베이스 구조를 설정하는 SQL문장이다. 기본적으로 스키마 객체를 생성, 변경, 제거하기 위해 사용되지만 DDL은 그 외 특권과 역할을 부여 및 감시 그리고 테이블 객체에 대한 최적화를 위한 명령어 또한 존재한다., k : 테이블 객체, q : 데이터 정의어는 무엇의 대한 최적화를 위한 명령어가 존재하는가?, num : 2
9 d : CHAR 타입은 고정된 문자열 길이를 저장하는 데이터 타입이다. VARCHAR 타입은 가변 길이를 갖는 문자열을 저장하는 데이터 타입이다. NCHAR 타입은 고정된 유니코드 문자열을 저장하는 데이터 타입니다. NVARCHAR 타입은 가변 길이를 갖는 유니코드 문자열을 저장하는 데이터 타입니다. SQL문장에서 CHAR, VARCHAR, NCHAR, NVARCHAR 타입을 표현할 때 작은따옴표를 사용한다. 문자열의 길이가 0이면 NULL로 인식한다. RAW 타입은 선언된 최대 길이 내에서 바이너리 데이터를 저장하고 중간에 NULL 문자가 올 수 있는 데이터 타입니다. LONG과 LONG RAW 타입은 각각 최대 2GB 까지 선언할 수 있는 VARCHAR과 RAW의 확장한 데이터 타입이다. LONG과 LONG RAW 타입에 접근할 때는 순차적으로만 접근 가능하며 테이블 내에 한 컬럼에만 선언 가능하다., k : CHAR, q : 고정된 문자열 길이를 저장하는 데이터 타입은 무엇인가?, num : 3
10 d : CHAR 타입은 고정된 문자열 길이를 저장하는 데이터 타입이다. VARCHAR 타입은 가변 길이를 갖는 문자열을 저장하는 데이터 타입이다. NCHAR 타입은 고정된 유니코드 문자열을 저장하는 데이터 타입니다. NVARCHAR 타입은 가변 길이를 갖는 유니코드 문자열을 저장하는 데이터 타입니다. SQL문장에서 CHAR, VARCHAR, NCHAR, NVARCHAR 타입을 표현할 때 작은따옴표를 사용한다. 문자열의 길이가 0이면 NULL로 인식한다. RAW 타입은 선언된 최대 길이 내에서 바이너리 데이터를 저장하고 중간에 NULL 문자가 올 수 있는 데이터 타입니다. LONG과 LONG RAW 타입은 각각 최대 2GB 까지 선언할 수 있는 VARCHAR과 RAW의 확장한 데이터 타입이다. LONG과 LONG RAW 타입에 접근할 때는 순차적으로만 접근 가능하며 테이블 내에 한 컬럼에만 선언 가능하다., k : VARCHAR, q : 가변 길이의 문자열을 저장하는 데이터 타입은 무엇인가?, num : 3
11 d : CHAR 타입은 고정된 문자열 길이를 저장하는 데이터 타입이다. VARCHAR 타입은 가변 길이를 갖는 문자열을 저장하는 데이터 타입이다. NCHAR 타입은 고정된 유니코드 문자열을 저장하는 데이터 타입니다. NVARCHAR 타입은 가변 길이를 갖는 유니코드 문자열을 저장하는 데이터 타입니다. SQL문장에서 CHAR, VARCHAR, NCHAR, NVARCHAR 타입을 표현할 때 작은따옴표를 사용한다. 문자열의 길이가 0이면 NULL로 인식한다. RAW 타입은 선언된 최대 길이 내에서 바이너리 데이터를 저장하고 중간에 NULL 문자가 올 수 있는 데이터 타입니다. LONG과 LONG RAW 타입은 각각 최대 2GB 까지 선언할 수 있는 VARCHAR과 RAW의 확장한 데이터 타입이다. LONG과 LONG RAW 타입에 접근할 때는 순차적으로만 접근 가능하며 테이블 내에 한 컬럼에만 선언 가능하다., k : NCHAR, q : 고정된 유니코드 문자열을 저장하는 데이터 타입은 무엇인가?, num : 3
12 d : CHAR 타입은 고정된 문자열 길이를 저장하는 데이터 타입이다. VARCHAR 타입은 가변 길이를 갖는 문자열을 저장하는 데이터 타입이다. NCHAR 타입은 고정된 유니코드 문자열을 저장하는 데이터 타입니다. NVARCHAR 타입은 가변 길이를 갖는 유니코드 문자열을 저장하는 데이터 타입니다. SQL문장에서 CHAR, VARCHAR, NCHAR, NVARCHAR 타입을 표현할 때 작은따옴표를 사용한다. 문자열의 길이가 0이면 NULL로 인식한다. RAW 타입은 선언된 최대 길이 내에서 바이너리 데이터를 저장하고 중간에 NULL 문자가 올 수 있는 데이터 타입니다. LONG과 LONG RAW 타입은 각각 최대 2GB 까지 선언할 수 있는 VARCHAR과 RAW의 확장한 데이터 타입이다. LONG과 LONG RAW 타입에 접근할 때는 순차적으로만 접근 가능하며 테이블 내에 한 컬럼에만 선언 가능하다., k : NVARCHAR, q : 가변 길이의 유니코드 문자열을 저장하는 데이터 타입은 무엇인가?, num : 3
13 d : CHAR 타입은 고정된 문자열 길이를 저장하는 데이터 타입이다. VARCHAR 타입은 가변 길이를 갖는 문자열을 저장하는 데이터 타입이다. NCHAR 타입은 고정된 유니코드 문자열을 저장하는 데이터 타입니다. NVARCHAR 타입은 가변 길이를 갖는 유니코드 문자열을 저장하는 데이터 타입니다. SQL문장에서 CHAR, VARCHAR, NCHAR, NVARCHAR 타입을 표현할 때 작은따옴표를 사용한다. 문자열의 길이가 0이면 NULL로 인식한다. RAW 타입은 선언된 최대 길이 내에서 바이너리 데이터를 저장하고 중간에 NULL 문자가 올 수 있는 데이터 타입니다. LONG과 LONG RAW 타입은 각각 최대 2GB 까지 선언할 수 있는 VARCHAR과 RAW의 확장한 데이터 타입이다. LONG과 LONG RAW 타입에 접근할 때는 순차적으로만 접근 가능하며 테이블 내에 한 컬럼에만 선언 가능하다., k : 작은따옴표, q : SQL 문장에서 문자열을 표현하는 문자는 무엇인가?, num : 3
14 d : CHAR 타입은 고정된 문자열 길이를 저장하는 데이터 타입이다. VARCHAR 타입은 가변 길이를 갖는 문자열을 저장하는 데이터 타입이다. NCHAR 타입은 고정된 유니코드 문자열을 저장하는 데이터 타입니다. NVARCHAR 타입은 가변 길이를 갖는 유니코드 문자열을 저장하는 데이터 타입니다. SQL문장에서 CHAR, VARCHAR, NCHAR, NVARCHAR 타입을 표현할 때 작은따옴표를 사용한다. 문자열의 길이가 0이면 NULL로 인식한다. RAW 타입은 선언된 최대 길이 내에서 바이너리 데이터를 저장하고 중간에 NULL 문자가 올 수 있는 데이터 타입니다. LONG과 LONG RAW 타입은 각각 최대 2GB 까지 선언할 수 있는 VARCHAR과 RAW의 확장한 데이터 타입이다. LONG과 LONG RAW 타입에 접근할 때는 순차적으로만 접근 가능하며 테이블 내에 한 컬럼에만 선언 가능하다., k : NULL, q : 문자열의 길이가 0일때 무엇으로 인식하는가?, num : 3
15 d : CHAR 타입은 고정된 문자열 길이를 저장하는 데이터 타입이다. VARCHAR 타입은 가변 길이를 갖는 문자열을 저장하는 데이터 타입이다. NCHAR 타입은 고정된 유니코드 문자열을 저장하는 데이터 타입니다. NVARCHAR 타입은 가변 길이를 갖는 유니코드 문자열을 저장하는 데이터 타입니다. SQL문장에서 CHAR, VARCHAR, NCHAR, NVARCHAR 타입을 표현할 때 작은따옴표를 사용한다. 문자열의 길이가 0이면 NULL로 인식한다. RAW 타입은 선언된 최대 길이 내에서 바이너리 데이터를 저장하고 중간에 NULL 문자가 올 수 있는 데이터 타입니다. LONG과 LONG RAW 타입은 각각 최대 2GB 까지 선언할 수 있는 VARCHAR과 RAW의 확장한 데이터 타입이다. LONG과 LONG RAW 타입에 접근할 때는 순차적으로만 접근 가능하며 테이블 내에 한 컬럼에만 선언 가능하다., k : RAW, q : 선언된 최대 길이 내에서 바이너리 데이터를 저장하는 데이터 타입은 무엇인가?, num : 3
16 d : CHAR 타입은 고정된 문자열 길이를 저장하는 데이터 타입이다. VARCHAR 타입은 가변 길이를 갖는 문자열을 저장하는 데이터 타입이다. NCHAR 타입은 고정된 유니코드 문자열을 저장하는 데이터 타입니다. NVARCHAR 타입은 가변 길이를 갖는 유니코드 문자열을 저장하는 데이터 타입니다. SQL문장에서 CHAR, VARCHAR, NCHAR, NVARCHAR 타입을 표현할 때 작은따옴표를 사용한다. 문자열의 길이가 0이면 NULL로 인식한다. RAW 타입은 선언된 최대 길이 내에서 바이너리 데이터를 저장하고 중간에 NULL 문자가 올 수 있는 데이터 타입니다. LONG과 LONG RAW 타입은 각각 최대 2GB 까지 선언할 수 있는 VARCHAR과 RAW의 확장한 데이터 타입이다. LONG과 LONG RAW 타입에 접근할 때는 순차적으로만 접근 가능하며 테이블 내에 한 컬럼에만 선언 가능하다., k : LONG과 LONG RAW, q : 최대 2GB 까지 선언할 수 있는 VARCHAR과 RAW의 확장한 데이터 타입은 무엇인가?, num : 3
17 d : CHAR 타입은 고정된 문자열 길이를 저장하는 데이터 타입이다. VARCHAR 타입은 가변 길이를 갖는 문자열을 저장하는 데이터 타입이다. NCHAR 타입은 고정된 유니코드 문자열을 저장하는 데이터 타입니다. NVARCHAR 타입은 가변 길이를 갖는 유니코드 문자열을 저장하는 데이터 타입니다. SQL문장에서 CHAR, VARCHAR, NCHAR, NVARCHAR 타입을 표현할 때 작은따옴표를 사용한다. 문자열의 길이가 0이면 NULL로 인식한다. RAW 타입은 선언된 최대 길이 내에서 바이너리 데이터를 저장하고 중간에 NULL 문자가 올 수 있는 데이터 타입니다. LONG과 LONG RAW 타입은 각각 최대 2GB 까지 선언할 수 있는 VARCHAR과 RAW의 확장한 데이터 타입이다. LONG과 LONG RAW 타입에 접근할 때는 순차적으로만 접근 가능하며 테이블 내에 한 컬럼에만 선언 가능하다., k : 순차적, q : LONG과 LONG RAW는 데이터를 어떤 방식으로만 접근이 가능한가?, num : 3
18 d : CHAR 타입은 고정된 문자열 길이를 저장하는 데이터 타입이다. VARCHAR 타입은 가변 길이를 갖는 문자열을 저장하는 데이터 타입이다. NCHAR 타입은 고정된 유니코드 문자열을 저장하는 데이터 타입니다. NVARCHAR 타입은 가변 길이를 갖는 유니코드 문자열을 저장하는 데이터 타입니다. SQL문장에서 CHAR, VARCHAR, NCHAR, NVARCHAR 타입을 표현할 때 작은따옴표를 사용한다. 문자열의 길이가 0이면 NULL로 인식한다. RAW 타입은 선언된 최대 길이 내에서 바이너리 데이터를 저장하고 중간에 NULL 문자가 올 수 있는 데이터 타입니다. LONG과 LONG RAW 타입은 각각 최대 2GB 까지 선언할 수 있는 VARCHAR과 RAW의 확장한 데이터 타입이다. LONG과 LONG RAW 타입에 접근할 때는 순차적으로만 접근 가능하며 테이블 내에 한 컬럼에만 선언 가능하다., k : 한 컬럼, q : LONG과 LONG RAW는 테이블 내에 몇 개의 컬럼에만 선언이 가능한가?, num : 3
19 d : 숫자형은 정수나 실수를 저장하는 데이터 타입이다. 티베로에서는 ANSI에서 제정한 SQL 표준의 숫자 타입인 NUMBER 타입을 지원한다. NUMBER 타입은 정밀도와 스케일을 함께 정의할 수 있다. 만약 생략될 경우, 가능한 최대 범위와 최대 정밀도 내에서 데이터 값은 지원한다. BINARY FLOAT은 32비트로 저장하는 데이터 타입이다. BINARY DOUBLE은 64비트로 저장하는 2배 정밀도 데이터 타입이다. BINARY FLOAT과 BINARY DOUBLE은 각종 변환함수 및 수학함수를 수행할 수 있는 데이터 타입이다. 티베로에서의 숫자형 우선 순위는 BINARY DOUBLE, BINARY FLOAT, NUMBER 순이다., k : 숫자형, q : 정수나 실수를 저장하는 데이터 타입은 무엇인가?, num : 4
20 d : 숫자형은 정수나 실수를 저장하는 데이터 타입이다. 티베로에서는 ANSI에서 제정한 SQL 표준의 숫자 타입인 NUMBER 타입을 지원한다. NUMBER 타입은 정밀도와 스케일을 함께 정의할 수 있다. 만약 생략될 경우, 가능한 최대 범위와 최대 정밀도 내에서 데이터 값은 지원한다. BINARY FLOAT은 32비트로 저장하는 데이터 타입이다. BINARY DOUBLE은 64비트로 저장하는 2배 정밀도 데이터 타입이다. BINARY FLOAT과 BINARY DOUBLE은 각종 변환함수 및 수학함수를 수행할 수 있는 데이터 타입이다. 티베로에서의 숫자형 우선 순위는 BINARY DOUBLE, BINARY FLOAT, NUMBER 순이다., k : NUMBER, q : 티베로에서는 어떤 숫자 타입을 지원하는가?, num : 4
21 d : 숫자형은 정수나 실수를 저장하는 데이터 타입이다. 티베로에서는 ANSI에서 제정한 SQL 표준의 숫자 타입인 NUMBER 타입을 지원한다. NUMBER 타입은 정밀도와 스케일을 함께 정의할 수 있다. 만약 생략될 경우, 가능한 최대 범위와 최대 정밀도 내에서 데이터 값은 지원한다. BINARY FLOAT은 32비트로 저장하는 데이터 타입이다. BINARY DOUBLE은 64비트로 저장하는 2배 정밀도 데이터 타입이다. BINARY FLOAT과 BINARY DOUBLE은 각종 변환함수 및 수학함수를 수행할 수 있는 데이터 타입이다. 티베로에서의 숫자형 우선 순위는 BINARY DOUBLE, BINARY FLOAT, NUMBER 순이다., k : 정밀도와 스케일, q : NUMBER 타입에서 무엇을 함께 정의할 수 있는가?, num : 4
22 d : 숫자형은 정수나 실수를 저장하는 데이터 타입이다. 티베로에서는 ANSI에서 제정한 SQL 표준의 숫자 타입인 NUMBER 타입을 지원한다. NUMBER 타입은 정밀도와 스케일을 함께 정의할 수 있다. 만약 생략될 경우, 가능한 최대 범위와 최대 정밀도 내에서 데이터 값은 지원한다. BINARY FLOAT은 32비트로 저장하는 데이터 타입이다. BINARY DOUBLE은 64비트로 저장하는 2배 정밀도 데이터 타입이다. BINARY FLOAT과 BINARY DOUBLE은 각종 변환함수 및 수학함수를 수행할 수 있는 데이터 타입이다. 티베로에서의 숫자형 우선 순위는 BINARY DOUBLE, BINARY FLOAT, NUMBER 순이다., k : 최대 범위와 최대 정밀도, q : 정밀도와 스케일이 생략될 경우 어떤 기준 내에서 데이터 값을 지원하는가?, num : 4
23 d : 숫자형은 정수나 실수를 저장하는 데이터 타입이다. 티베로에서는 ANSI에서 제정한 SQL 표준의 숫자 타입인 NUMBER 타입을 지원한다. NUMBER 타입은 정밀도와 스케일을 함께 정의할 수 있다. 만약 생략될 경우, 가능한 최대 범위와 최대 정밀도 내에서 데이터 값은 지원한다. BINARY FLOAT은 32비트로 저장하는 데이터 타입이다. BINARY DOUBLE은 64비트로 저장하는 2배 정밀도 데이터 타입이다. BINARY FLOAT과 BINARY DOUBLE은 각종 변환함수 및 수학함수를 수행할 수 있는 데이터 타입이다. 티베로에서의 숫자형 우선 순위는 BINARY DOUBLE, BINARY FLOAT, NUMBER 순이다., k : BINARY FLOAT, q : 32비트로 저장하는 데이터 타입은 무엇인가?, num : 4
24 d : 숫자형은 정수나 실수를 저장하는 데이터 타입이다. 티베로에서는 ANSI에서 제정한 SQL 표준의 숫자 타입인 NUMBER 타입을 지원한다. NUMBER 타입은 정밀도와 스케일을 함께 정의할 수 있다. 만약 생략될 경우, 가능한 최대 범위와 최대 정밀도 내에서 데이터 값은 지원한다. BINARY FLOAT은 32비트로 저장하는 데이터 타입이다. BINARY DOUBLE은 64비트로 저장하는 2배 정밀도 데이터 타입이다. BINARY FLOAT과 BINARY DOUBLE은 각종 변환함수 및 수학함수를 수행할 수 있는 데이터 타입이다. 티베로에서의 숫자형 우선 순위는 BINARY DOUBLE, BINARY FLOAT, NUMBER 순이다., k : BINARY DOUBLE, q : 64 비트로 저장하는 2배 정밀도 데이터 타입은 무엇인가?, num : 4
25 d : 숫자형은 정수나 실수를 저장하는 데이터 타입이다. 티베로에서는 ANSI에서 제정한 SQL 표준의 숫자 타입인 NUMBER 타입을 지원한다. NUMBER 타입은 정밀도와 스케일을 함께 정의할 수 있다. 만약 생략될 경우, 가능한 최대 범위와 최대 정밀도 내에서 데이터 값은 지원한다. BINARY FLOAT은 32비트로 저장하는 데이터 타입이다. BINARY DOUBLE은 64비트로 저장하는 2배 정밀도 데이터 타입이다. BINARY FLOAT과 BINARY DOUBLE은 각종 변환함수 및 수학함수를 수행할 수 있는 데이터 타입이다. 티베로에서의 숫자형 우선 순위는 BINARY DOUBLE, BINARY FLOAT, NUMBER 순이다., k : 변환함수 및 수학함수, q : BINARY FLOAT과 BINARY DOUBLE은 무엇을 수행할 수 있는 데이터 타입인가?, num : 4
26 d : 숫자형은 정수나 실수를 저장하는 데이터 타입이다. 티베로에서는 ANSI에서 제정한 SQL 표준의 숫자 타입인 NUMBER 타입을 지원한다. NUMBER 타입은 정밀도와 스케일을 함께 정의할 수 있다. 만약 생략될 경우, 가능한 최대 범위와 최대 정밀도 내에서 데이터 값은 지원한다. BINARY FLOAT은 32비트로 저장하는 데이터 타입이다. BINARY DOUBLE은 64비트로 저장하는 2배 정밀도 데이터 타입이다. BINARY FLOAT과 BINARY DOUBLE은 각종 변환함수 및 수학함수를 수행할 수 있는 데이터 타입이다. 티베로에서의 숫자형 우선 순위는 BINARY DOUBLE, BINARY FLOAT, NUMBER 순이다., k : BINARY DOUBLE, BINARY FLOAT, NUMBER, q : 티베로에서의 숫자형 우선순위는 어떻게 되는가?, num : 4
27 d : 날짜형은 시간과 날짜를 저장한다. DATE 타입은 날짜와 초 단위까지 저장하는 데이터 타입이다. TIME 타입은 소수점 9자리 까지의 초 단위를 저장하는 데이터 타입이다. TIMESTAMP 타입은 소수점 9자리 까지의 날짜와 초 단위를 저장하는 데이터 타입니다. TIMESTAMP WITH TIME ZONE 타입은 TIMESTAMP의 확장형인 시간대까지 저장하는 타입니다. TIMESTAMP WITH LOCAL TIME ZONE 타입은 특정 세션의 시간대도 저장하는 타입니다., k : 날짜형, q : 시간과 날짜를 저장하는 데이터 타입은 무엇인가?, num : 5
28 d : 날짜형은 시간과 날짜를 저장한다. DATE 타입은 날짜와 초 단위까지 저장하는 데이터 타입이다. TIME 타입은 소수점 9자리 까지의 초 단위를 저장하는 데이터 타입이다. TIMESTAMP 타입은 소수점 9자리 까지의 날짜와 초 단위를 저장하는 데이터 타입니다. TIMESTAMP WITH TIME ZONE 타입은 TIMESTAMP의 확장형인 시간대까지 저장하는 타입니다. TIMESTAMP WITH LOCAL TIME ZONE 타입은 특정 세션의 시간대도 저장하는 타입니다., k : DATE, q : 날짜와 초 단위까지 저장하는 데이터 타입은 무엇인가?, num : 5
29 d : 날짜형은 시간과 날짜를 저장한다. DATE 타입은 날짜와 초 단위까지 저장하는 데이터 타입이다. TIME 타입은 소수점 9자리 까지의 초 단위를 저장하는 데이터 타입이다. TIMESTAMP 타입은 소수점 9자리 까지의 날짜와 초 단위를 저장하는 데이터 타입니다. TIMESTAMP WITH TIME ZONE 타입은 TIMESTAMP의 확장형인 시간대까지 저장하는 타입니다. TIMESTAMP WITH LOCAL TIME ZONE 타입은 특정 세션의 시간대도 저장하는 타입니다., k : TIME, q : 소수점 9자리 까지의 초 단위를 저장하는 데이터 타입은 무엇인가?, num : 5
30 d : 날짜형은 시간과 날짜를 저장한다. DATE 타입은 날짜와 초 단위까지 저장하는 데이터 타입이다. TIME 타입은 소수점 9자리 까지의 초 단위를 저장하는 데이터 타입이다. TIMESTAMP 타입은 소수점 9자리 까지의 날짜와 초 단위를 저장하는 데이터 타입니다. TIMESTAMP WITH TIME ZONE 타입은 TIMESTAMP의 확장형인 시간대까지 저장하는 타입니다. TIMESTAMP WITH LOCAL TIME ZONE 타입은 특정 세션의 시간대도 저장하는 타입니다., k : TIMESTAMP, q : 소수점 9자리 까지의 날짜와 초 단위를 저장하는 데이터 타입은 무엇인가?, num : 5
31 d : 날짜형은 시간과 날짜를 저장한다. DATE 타입은 날짜와 초 단위까지 저장하는 데이터 타입이다. TIME 타입은 소수점 9자리 까지의 초 단위를 저장하는 데이터 타입이다. TIMESTAMP 타입은 소수점 9자리 까지의 날짜와 초 단위를 저장하는 데이터 타입니다. TIMESTAMP WITH TIME ZONE 타입은 TIMESTAMP의 확장형인 시간대까지 저장하는 타입니다. TIMESTAMP WITH LOCAL TIME ZONE 타입은 특정 세션의 시간대도 저장하는 타입니다., k : TIMESTAMP WITH TIME ZONE, q : TIMESTAMP 데이터 타입의 확장형이며 시간대까지 저장하는 데이터 타입은 무엇인가?, num : 5
32 d : 날짜형은 시간과 날짜를 저장한다. DATE 타입은 날짜와 초 단위까지 저장하는 데이터 타입이다. TIME 타입은 소수점 9자리 까지의 초 단위를 저장하는 데이터 타입이다. TIMESTAMP 타입은 소수점 9자리 까지의 날짜와 초 단위를 저장하는 데이터 타입니다. TIMESTAMP WITH TIME ZONE 타입은 TIMESTAMP의 확장형인 시간대까지 저장하는 타입니다. TIMESTAMP WITH LOCAL TIME ZONE 타입은 특정 세션의 시간대도 저장하는 타입니다., k : TIMESTAMP WITH LOCAL TIME ZONE, q : 특정 세션의 시간대도 저장하는 데이터 타입은 무엇인가?, num : 5
33 d : 간격형은 시간과 날짜 사이의 간격을 저정하는 데이터 타입이다. INTERVAL YEAR TO MONTH 타입은 연도와 월의 간격을 저장하는 데이터 타입니다. INTERVAL DAY TO SECOND 타입은 일, 시, 분, 초의 간격을 저장하는 데이터 타입이다., k : 간격형, q : 시간과 날짜 사이의 간격을 저장하는 데이터 타입은 무엇인가?, num : 6
34 d : 간격형은 시간과 날짜 사이의 간격을 저정하는 데이터 타입이다. INTERVAL YEAR TO MONTH 타입은 연도와 월의 간격을 저장하는 데이터 타입니다. INTERVAL DAY TO SECOND 타입은 일, 시, 분, 초의 간격을 저장하는 데이터 타입이다., k : INTERVAL YEAR TO MONTH, q : 연도와 월의 간격을 저장하는 데이터 타입은 무엇인가?, num : 6
35 d : 간격형은 시간과 날짜 사이의 간격을 저정하는 데이터 타입이다. INTERVAL YEAR TO MONTH 타입은 연도와 월의 간격을 저장하는 데이터 타입니다. INTERVAL DAY TO SECOND 타입은 일, 시, 분, 초의 간격을 저장하는 데이터 타입이다., k : INTERVAL DAY TO SECOND, q : 일, 시, 분, 초의 간격을 저장하는 데이터 타입은 무엇인가?, num : 6
36 d : 대용량 객체형은 티베로에서 제공하는 가장 큰 데이터 타입이다. CLOB과 BLOB 타입은 각각 LONG과 LONG RAW 타입의 확장형이며 최대 4GB까지 저장 가능하다. CLOB과 BLOB 타입은 각각 LONG과 LONG RAW 타입과 달리 임의의 위치로 접근 가능하며 한 컬럼 이상 선언 가능하다., k : 대용량 객체형, q : 티베로에서 제공하는 가장 큰 데이터 타입은 무엇인가?, num : 7
37 d : 대용량 객체형은 티베로에서 제공하는 가장 큰 데이터 타입이다. CLOB과 BLOB 타입은 각각 LONG과 LONG RAW 타입의 확장형이며 최대 4GB까지 저장 가능하다. CLOB과 BLOB 타입은 각각 LONG과 LONG RAW 타입과 달리 임의의 위치로 접근 가능하며 한 컬럼 이상 선언 가능하다., k : CLOB과 BLOB, q : LONG과 LONG RAW 타입의 확장형이며 최대 4GB까지 저장 가능한 데이터 타입은 무엇인가?, num : 7
38 d : 대용량 객체형은 티베로에서 제공하는 가장 큰 데이터 타입이다. CLOB과 BLOB 타입은 각각 LONG과 LONG RAW 타입의 확장형이며 최대 4GB까지 저장 가능하다. CLOB과 BLOB 타입은 각각 LONG과 LONG RAW 타입과 달리 임의의 위치로 접근 가능하며 한 컬럼 이상 선언 가능하다., k : 임의의 위치, q : CLOB과 BLOB는 LONG과 LONG RAW와 달리 어떻게 접근이 가능한가?, num : 7
39 d : 대용량 객체형은 티베로에서 제공하는 가장 큰 데이터 타입이다. CLOB과 BLOB 타입은 각각 LONG과 LONG RAW 타입의 확장형이며 최대 4GB까지 저장 가능하다. CLOB과 BLOB 타입은 각각 LONG과 LONG RAW 타입과 달리 임의의 위치로 접근 가능하며 한 컬럼 이상 선언 가능하다., k : 한 컬럼 이상, q : CLOB과 BLOB는 LONG과 LONG RAW와 달리 몇 개의 컬럼을 선언할 수 있는가?, num : 7
40 d : 사용자 정의형은 사용자가 정의하는 데이터 타입이다. tbPSM 타입으로 사용가능하며, 티베로 서버에 저장된다. 배열은 최대 배열 길이를 가지는 사용자 정의 타입이다. 네스티드 테이블은 최대 배열 길이가 없는 사용자 정의 타입이다., k : 사용자 정의형, q : 사용자가 정의하는 데이터 타입은 무엇인가?, num : 8
41 d : 사용자 정의형은 사용자가 정의하는 데이터 타입이다. tbPSM 타입으로 사용가능하며, 티베로 서버에 저장된다. 배열은 최대 배열 길이를 가지는 사용자 정의 타입이다. 네스티드 테이블은 최대 배열 길이가 없는 사용자 정의 타입이다., k : 티베로 서버, q : 사용자 정의형은 어디에 저장 되는가?, num : 8
42 d : 사용자 정의형은 사용자가 정의하는 데이터 타입이다. tbPSM 타입으로 사용가능하며, 티베로 서버에 저장된다. 배열은 최대 배열 길이를 가지는 사용자 정의 타입이다. 네스티드 테이블은 최대 배열 길이가 없는 사용자 정의 타입이다., k : 배열, q : 최대 배열 길이를 가지는 사용자 정의 타입은 무엇인가?, num : 8
43 d : 사용자 정의형은 사용자가 정의하는 데이터 타입이다. tbPSM 타입으로 사용가능하며, 티베로 서버에 저장된다. 배열은 최대 배열 길이를 가지는 사용자 정의 타입이다. 네스티드 테이블은 최대 배열 길이가 없는 사용자 정의 타입이다., k : 네스티드 테이블, q : 최대 배열 길이가 없는 사용자 정의 타입은 무엇인가?, num : 8
44 d : 형식 문자열은 숫자형과 날짜형을 문자열로 변환하는 형식을 정의한 것이다. 또한, 변환 뿐만 아니라 반대로 변환된 숫자형과 날짜형을 다시 복구하는데 필요하다. 정해진 시간 형식이 아니거나 숫자와 문자를 동시에 포함하는 문자열은 날짜형과 숫자형으로 변환할 수 없다., k : 형식 문자열, q : 숫자형과 날짜형을 문자열로 변환하는 형식을 정의한 것은?, num : 9
45 d : 형식 문자열은 숫자형과 날짜형을 문자열로 변환하는 형식을 정의한 것이다. 또한, 변환 뿐만 아니라 반대로 변환된 숫자형과 날짜형을 다시 복구하는데 필요하다. 정해진 시간 형식이 아니거나 숫자와 문자를 동시에 포함하는 문자열은 날짜형과 숫자형으로 변환할 수 없다., k : 복구, q : 변환 뿐만 아니라 무엇을 할 때 형식 문자열이 필요한가?, num : 9
46 d : 형식 문자열은 숫자형과 날짜형을 문자열로 변환하는 형식을 정의한 것이다. 또한, 변환 뿐만 아니라 반대로 변환된 숫자형과 날짜형을 다시 복구하는데 필요하다. 정해진 시간 형식이 아니거나 숫자와 문자를 동시에 포함하는 문자열은 날짜형과 숫자형으로 변환할 수 없다., k : 정해진 시간 형식, q : 문자열이 무엇이 아니면 날짜형으로 변환할 수 없는가?, num : 9
47 d : 형식 문자열은 숫자형과 날짜형을 문자열로 변환하는 형식을 정의한 것이다. 또한, 변환 뿐만 아니라 반대로 변환된 숫자형과 날짜형을 다시 복구하는데 필요하다. 정해진 시간 형식이 아니거나 숫자와 문자를 동시에 포함하는 문자열은 날짜형과 숫자형으로 변환할 수 없다., k : 숫자와 문자, q : 문자열에 어떤 두 문자가 포함되면 숫자형으로 변활할 수 없는가?, num : 9
48 d : SQL문장과 스키마 객체에는 주석을 삽입할 수 있다. 주석을 활용하여 특정 SQL 문장을 더 자세히 설명할 수 있다. 따라서 주석은 애플리케이션의 코드를 효율적으로 관리하는데 도움을 준다. 또한 주석은 SQL 문장의 실행에는 영향을 끼치지 않는다., k : 주석, q : SQL문장과 스키마 객체에 무엇을 삽입할 수 있는가?, num : 10
49 d : SQL문장과 스키마 객체에는 주석을 삽입할 수 있다. 주석을 활용하여 특정 SQL 문장을 더 자세히 설명할 수 있다. 따라서 주석은 애플리케이션의 코드를 효율적으로 관리하는데 도움을 준다. 또한 주석은 SQL 문장의 실행에는 영향을 끼치지 않는다., k : 더 자세히 설명, q : 주석을 활용하면 특정 SQL 문장에 대해 무엇을 할 수 있는가?, num : 10
50 d : SQL문장과 스키마 객체에는 주석을 삽입할 수 있다. 주석을 활용하여 특정 SQL 문장을 더 자세히 설명할 수 있다. 따라서 주석은 애플리케이션의 코드를 효율적으로 관리하는데 도움을 준다. 또한 주석은 SQL 문장의 실행에는 영향을 끼치지 않는다., k : 효율적, q : 주석은 애플리케이션의 코드를 어떤 방식으로 관리할 수 있는가?, num : 10
51 d : SQL문장과 스키마 객체에는 주석을 삽입할 수 있다. 주석을 활용하여 특정 SQL 문장을 더 자세히 설명할 수 있다. 따라서 주석은 애플리케이션의 코드를 효율적으로 관리하는데 도움을 준다. 또한 주석은 SQL 문장의 실행에는 영향을 끼치지 않는다., k : SQL 문장의 실행, q : 주석은 무엇에 영향을 끼치지 않는가?, num : 10
52 d : 인덱스는 특정 컬럼을 빠르게 검색 할 수 있도록 해주는 데이터 구조이다. 자동 인덱싱은 티베로 모든 테이블의 기본 키 컬럼에 자동으로 생성한다. 인덱스는 한 컬럼에 중복 생성과 복수 컬럼에 단일 생성이 가능하다. 인덱스를 사용할 때와 사용하지 않을 때의 효율을 비교하여 적용할지에 대한 여부는 데이터베이스 시스템에서 자동으로 결정한다., k : 인덱스, q : 특정 컬럼을 빠르게 검색 할 수 있도록 해주는 데이터 구조는 무엇인가?, num : 11
53 d : 인덱스는 특정 컬럼을 빠르게 검색 할 수 있도록 해주는 데이터 구조이다. 자동 인덱싱은 티베로 모든 테이블의 기본 키 컬럼에 자동으로 생성한다. 인덱스는 한 컬럼에 중복 생성과 복수 컬럼에 단일 생성이 가능하다. 인덱스를 사용할 때와 사용하지 않을 때의 효율을 비교하여 적용할지에 대한 여부는 데이터베이스 시스템에서 자동으로 결정한다., k : 자동 인덱싱, q : 모든 테이블의 기본 키 컬럼에 자동으로 생성되는 것은 무엇인가?, num : 11
54 d : 인덱스는 특정 컬럼을 빠르게 검색 할 수 있도록 해주는 데이터 구조이다. 자동 인덱싱은 티베로 모든 테이블의 기본 키 컬럼에 자동으로 생성한다. 인덱스는 한 컬럼에 중복 생성과 복수 컬럼에 단일 생성이 가능하다. 인덱스를 사용할 때와 사용하지 않을 때의 효율을 비교하여 적용할지에 대한 여부는 데이터베이스 시스템에서 자동으로 결정한다., k : 중복 생성과 단일 생성, q : 인덱스는 한 컬럼과 복수 컬럼에 무엇이 가능한가?, num : 11
55 d : 인덱스는 특정 컬럼을 빠르게 검색 할 수 있도록 해주는 데이터 구조이다. 자동 인덱싱은 티베로 모든 테이블의 기본 키 컬럼에 자동으로 생성한다. 인덱스는 한 컬럼에 중복 생성과 복수 컬럼에 단일 생성이 가능하다. 인덱스를 사용할 때와 사용하지 않을 때의 효율을 비교하여 적용할지에 대한 여부는 데이터베이스 시스템에서 자동으로 결정한다., k : 데이터베이스 시스템, q : 인덱스를 사용할지 안할지에 대한 효율성 여부는 무엇이 판단하는가?, num : 11
56 d : 뷰는 자주 수행되는 질의의 결과를 테이블로 이용할 수 있도록 정의한다. 또한, 뷰는 정보 보안상의 이유로도 사용된다. 뷰 병합은 뷰를 포함한 SQL 문장이 주어지면 데이터베이스 시스템은 해당 문장을 뷰 미포함 SQL 문장으로 변환한다. 뷰를 정의한 사용자가 해당 뷰에 대한 접근 권한을 부여할 수 있다., k : 뷰, q : 자주 수행되는 질의의 결과를 테이블로 이용할 수 있도록 정의한것이 무엇인가?, num : 12
57 d : 뷰는 자주 수행되는 질의의 결과를 테이블로 이용할 수 있도록 정의한다. 또한, 뷰는 정보 보안상의 이유로도 사용된다. 뷰 병합은 뷰를 포함한 SQL 문장이 주어지면 데이터베이스 시스템은 해당 문장을 뷰 미포함 SQL 문장으로 변환한다. 뷰를 정의한 사용자가 해당 뷰에 대한 접근 권한을 부여할 수 있다., k : 정보 보안, q : 뷰는 어떠한 이유에서 사용되는가?, num : 12
58 d : 뷰는 자주 수행되는 질의의 결과를 테이블로 이용할 수 있도록 정의한다. 또한, 뷰는 정보 보안상의 이유로도 사용된다. 뷰 병합은 뷰를 포함한 SQL 문장이 주어지면 데이터베이스 시스템은 해당 문장을 뷰 미포함 SQL 문장으로 변환한다. 뷰를 정의한 사용자가 해당 뷰에 대한 접근 권한을 부여할 수 있다., k : 뷰 병합, q : 뷰를 포함한 SQL문장을 뷰 미포함 SQL 문장으로 변환하는 작업을 무엇이가 하는가?, num : 12
59 d : 뷰는 자주 수행되는 질의의 결과를 테이블로 이용할 수 있도록 정의한다. 또한, 뷰는 정보 보안상의 이유로도 사용된다. 뷰 병합은 뷰를 포함한 SQL 문장이 주어지면 데이터베이스 시스템은 해당 문장을 뷰 미포함 SQL 문장으로 변환한다. 뷰를 정의한 사용자가 해당 뷰에 대한 접근 권한을 부여할 수 있다., k : 접근 권한, q : 뷰를 정의한 사용자가 해당 뷰에 대한 어떤 것을 부여할 수 있는가?, num : 12
60 d : 동의어는 일종의 별칭이다. 동의어는 긴 이름 대신 사용한다. 동의어를 정의한 사용자만 사용가능하다. 모든 사용자가 사용하기 위해서는 공용으로 정의해야 하고 이를 공용 동의어라 부른다., k : 동의어, q : 일종의 별칭이라고 불리는 이것은 무엇인가?, num : 13
61 d : 동의어는 일종의 별칭이다. 동의어는 긴 이름 대신 사용한다. 동의어를 정의한 사용자만 사용가능하다. 모든 사용자가 사용하기 위해서는 공용으로 정의해야 하고 이를 공용 동의어라 부른다., k : 긴 이름, q : 공의어는 무엇 대신 사용하는가?, num : 13
62 d : 동의어는 일종의 별칭이다. 동의어는 긴 이름 대신 사용한다. 동의어를 정의한 사용자만 사용가능하다. 모든 사용자가 사용하기 위해서는 공용으로 정의해야 하고 이를 공용 동의어라 부른다., k : 정의한 사용자, q : 동의어는 누구만 사용 가능한가?, num : 13
63 d : 동의어는 일종의 별칭이다. 동의어는 긴 이름 대신 사용한다. 동의어를 정의한 사용자만 사용가능하다. 모든 사용자가 사용하기 위해서는 공용으로 정의해야 하고 이를 공용 동의어라 부른다., k : 공용 동의어, q : 동의어를 공용으로 정의하여 모든 사용자가 사용 가능한 동의어를 무엇이라 부르는가?, num : 13
64 d : 티베로의 함수는 단일 로우 함수와 집단 한수로 구분한다. 대부분의 함수는 하나 이상의 파라미터를 입력으로, 하나의 출력을 반환한다. NULL이 입력으로 들어오게 되면 대부분 함수는 NULL을 반환한다. 함수의 변환값 유의. 변환값이 NUMBER인 경우 컬럼의 정밀도와 스케일 범위 내여야 한다. 변환값이 CHAR혹은 VARCHAR인 경우 컬럼의 최대 길이 범위 내여야 한다., k : 단일 로우와 집단, q : 티베로의 함수는 무엇으로 구분되는가?, num : 14
65 d : 티베로의 함수는 단일 로우 함수와 집단 한수로 구분한다. 대부분의 함수는 하나 이상의 파라미터를 입력으로, 하나의 출력을 반환한다. NULL이 입력으로 들어오게 되면 대부분 함수는 NULL을 반환한다. 함수의 변환값 유의. 변환값이 NUMBER인 경우 컬럼의 정밀도와 스케일 범위 내여야 한다. 변환값이 CHAR혹은 VARCHAR인 경우 컬럼의 최대 길이 범위 내여야 한다., k : 하나의 출력, q : 대부분의 함수는 하나 이상의 파라미터를 입력으로 받고 무엇을 반환하는가?, num : 14
66 d : 티베로의 함수는 단일 로우 함수와 집단 한수로 구분한다. 대부분의 함수는 하나 이상의 파라미터를 입력으로, 하나의 출력을 반환한다. NULL이 입력으로 들어오게 되면 대부분 함수는 NULL을 반환한다. 함수의 변환값 유의. 변환값이 NUMBER인 경우 컬럼의 정밀도와 스케일 범위 내여야 한다. 변환값이 CHAR혹은 VARCHAR인 경우 컬럼의 최대 길이 범위 내여야 한다., k : NULL, q : NULL이 입력으로 들어오게 되면 대부분의 함수는 무엇을 반환하는가?, num : 14